export interface User {
  uid: string; // Firebase UID as primary key
  email: string | null;
  name: string | null;
  created_at: string;
}

export interface Session {
  id: string; // UUID generated by database
  uid: string; // References users.uid
  start_time: string;
  end_time: string | null;
  focus_mode: "quick-buzz" | "honey-flow" | "deep-nectar";
  status: "active" | "completed" | "cancelled";
  actual_focus_minutes: number;
  created_at: string;
}

export interface UserStats {
  uid: string; // References users.uid
  total_focus_minutes: number;
  total_sessions: number;
  completed_sessions: number;
  cancelled_sessions: number;
  last_session_at: string | null;
  longest_session_minutes: number;
  average_session_minutes: number;
  created_at: string;
  updated_at: string;
}

export type FocusMode = "quick-buzz" | "honey-flow" | "deep-nectar";
export type SessionStatus = "active" | "completed" | "cancelled";
