export interface User {
  uid: string;           // Firebase UID as primary key
  email: string | null;
  name: string | null;
  created_at: string;
}

export interface Session {
  id: string;            // UUID generated by database
  uid: string;           // References users.uid
  start_time: string;
  end_time: string | null;
  focus_mode: 'quick-buzz' | 'honey-flow' | 'deep-nectar';
  status: 'active' | 'completed' | 'cancelled';
  created_at: string;
}

export type FocusMode = 'quick-buzz' | 'honey-flow' | 'deep-nectar';
export type SessionStatus = 'active' | 'completed' | 'cancelled';
